log_level = "info"
server = "[::]:2020"
udp_relay_ipv6 = true
zero_rtt_handshake = false
dual_stack = true
auth_timeout = "3s"
task_negotiation_timeout = "3s"
gc_interval = "3s"
gc_lifetime = "15s"
max_external_packet_size = 1500

[users]
d3dd1630-02c8-42ff-9c5e-efbc0bec12c6 = "81c122cc-cf1a-4c0d-926b-18e4afe509ad"

[tls]
self_sign = false
certificate = "/etc/tuic/ca.crt"
private_key = "/etc/tuic/ca.key"
alpn = ["h3", "spdy/3.1"]

[restful]
addr = "127.0.0.1:32020"
secret = "81c122cc-cf1a-4c0d-926b-18e4afe509ad"
maximum_clients_per_user = 0

[quic]
initial_mtu = 1200
min_mtu = 1200
gso = true
pmtu = true
send_window = 16777216
receive_window = 8388608
max_idle_time = "10s"

[quic.congestion_control]
controller = "bbr"
initial_window = 1048576
