name: build ss-server-v2ray images

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "ss/**"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image and push
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ss
          VERSION=`cat Dockerfile | grep "ARG VERSION" | awk -F '=' '{print $2}'`
          echo $GITHUB_TOKEN | docker login ghcr.io -u onlyxxp --password-stdin
          docker buildx build --platform linux/amd64 -t ghcr.io/onlyxxp/ssserver2ray:$VERSION --squash --push .
